"""emailaddress

Revision ID: 410c63b113e4
Revises: f0b17ab53e0b
Create Date: 2020-10-25 20:54:06.022183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410c63b113e4'
down_revision = 'f0b17ab53e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_address',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_index(op.f('ix_email_address_created_at'), 'email_address', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_address_email_address'), 'email_address', ['email_address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_address_email_address'), table_name='email_address')
    op.drop_index(op.f('ix_email_address_created_at'), table_name='email_address')
    op.drop_table('email_address')
    # ### end Alembic commands ###
