"""added email_pref col

Revision ID: 47751d1f389f
Revises: 836ec65e3c1a
Create Date: 2021-01-20 21:29:18.739688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47751d1f389f'
down_revision = '836ec65e3c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_address', sa.Column('notification_preference', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_address', 'notification_preference')
    # ### end Alembic commands ###
