"""inc send_adr limit

Revision ID: 534d2f1040ca
Revises: 923836e9b856
Create Date: 2020-12-26 17:39:29.095711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534d2f1040ca'
down_revision = '923836e9b856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phishing_email', 'sender_address',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phishing_email', 'sender_address',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
