"""added total_mails_checked for EmailAddress, removed last_mailbox_size

Revision ID: 836ec65e3c1a
Revises: f0af26458f68
Create Date: 2021-01-16 23:38:27.417484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836ec65e3c1a'
down_revision = 'f0af26458f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_address', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('email_address', sa.Column('total_mails_checked', sa.Integer(), nullable=True))
    op.drop_constraint('email_address_user_id_fkey', 'email_address', type_='foreignkey')
    op.create_foreign_key(None, 'email_address', 'user', ['owner_id'], ['user_id'])
    op.drop_column('email_address', 'last_mailbox_size')
    op.drop_column('email_address', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_address', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('email_address', sa.Column('last_mailbox_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'email_address', type_='foreignkey')
    op.create_foreign_key('email_address_user_id_fkey', 'email_address', 'user', ['user_id'], ['user_id'])
    op.drop_column('email_address', 'total_mails_checked')
    op.drop_column('email_address', 'owner_id')
    # ### end Alembic commands ###
