"""added subject in to phishingemail model

Revision ID: 923836e9b856
Revises: 85dcee72b6c4
Create Date: 2020-12-25 13:26:58.921602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923836e9b856'
down_revision = '85dcee72b6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phishing_email', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.add_column('phishing_email', sa.Column('subject', sa.Text(), nullable=False))
    op.create_index(op.f('ix_phishing_email_receiver_id'), 'phishing_email', ['receiver_id'], unique=False)
    op.drop_index('ix_phishing_email_sender_address', table_name='phishing_email')
    op.create_index(op.f('ix_phishing_email_sender_address'), 'phishing_email', ['sender_address'], unique=False)
    op.drop_index('ix_phishing_email_receiver_address', table_name='phishing_email')
    op.drop_constraint('phishing_email_receiver_address_fkey', 'phishing_email', type_='foreignkey')
    op.create_foreign_key(None, 'phishing_email', 'email_address', ['receiver_id'], ['email_id'])
    op.drop_column('phishing_email', 'receiver_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phishing_email', sa.Column('receiver_address', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'phishing_email', type_='foreignkey')
    op.create_foreign_key('phishing_email_receiver_address_fkey', 'phishing_email', 'email_address', ['receiver_address'], ['email_id'])
    op.create_index('ix_phishing_email_receiver_address', 'phishing_email', ['receiver_address'], unique=False)
    op.drop_index(op.f('ix_phishing_email_sender_address'), table_name='phishing_email')
    op.create_index('ix_phishing_email_sender_address', 'phishing_email', ['sender_address'], unique=True)
    op.drop_index(op.f('ix_phishing_email_receiver_id'), table_name='phishing_email')
    op.drop_column('phishing_email', 'subject')
    op.drop_column('phishing_email', 'receiver_id')
    # ### end Alembic commands ###
