"""added reset_token to users

Revision ID: f0af26458f68
Revises: 534d2f1040ca
Create Date: 2021-01-02 21:47:24.593579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0af26458f68'
down_revision = '534d2f1040ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phishing_email', 'sender_address',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('user', sa.Column('reset_token', sa.Numeric(precision=6, scale=0), nullable=True))
    op.create_unique_constraint(None, 'user', ['reset_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'reset_token')
    op.alter_column('phishing_email', 'sender_address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
