"""add emailaddress table

Revision ID: f0b17ab53e0b
Revises: ee1c83c9fc10
Create Date: 2020-10-25 20:45:24.494673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b17ab53e0b'
down_revision = 'ee1c83c9fc10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
